-- Auto-generated from data/*.csv by supabase/scripts/csv-to-seed.ps1 - do not edit by hand.
-- Regenerate when the CSVs change.

-- grounding: drug_mapping (drug -> RXCUI -> class -> flags)
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('warfarin', '11289', 'anticoagulant', '1', '1');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('aspirin', '1191', 'nsaid_antiplatelet', '1', '1');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('ibuprofen', '5640', 'nsaid', '1', '1');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('acetaminophen', '161', 'analgesic', '0', '0');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('amoxicillin', '723', 'penicillin_antibiotic', '0', '0');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('clarithromycin', '2670', 'macrolide', '1', '1');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('fluconazole', '4440', 'azole_antifungal', '1', '1');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('simvastatin', '36567', 'statin', '1', '1');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('gemfibrozil', '24987', 'fibrate', '1', '1');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('digoxin', '3640', 'cardiac_glycoside', '1', '1');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('amiodarone', '703', 'antiarrhythmic', '1', '1');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('verapamil', '11170', 'calcium_channel_blocker', '1', '1');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('methotrexate', '6851', 'antimetabolite', '1', '1');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('trimethoprim', '10622', 'antibiotic', '1', '1');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('fluoxetine', '4493', 'ssri', '1', '1');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('phenelzine', '8134', 'maoi', '1', '1');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('sertraline', '9617', 'ssri', '1', '1');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('tramadol', '10871', 'opioid_analgesic', '1', '1');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('sildenafil', '36437', 'pde5_inhibitor', '1', '1');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('nitroglycerin', '3837', 'nitrate', '1', '1');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('lisinopril', '29046', 'ace_inhibitor', '0', '1');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('spironolactone', '10106', 'potassium_sparing_diuretic', '0', '1');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('lithium', '6518', 'mood_stabilizer', '1', '1');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('clopidogrel', '32968', 'antiplatelet', '1', '1');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('omeprazole', '7646', 'proton_pump_inhibitor', '1', '0');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('valproic acid', '11148', 'anticonvulsant', '1', '1');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('carbamazepine', '2000', 'anticonvulsant', '1', '1');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('levothyroxine', '10582', 'thyroid_hormone', '1', '1');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('calcium carbonate', '2061', 'antacid_supplement', '0', '0');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('theophylline', '10550', 'bronchodilator', '1', '1');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('ciprofloxacin', '2551', 'fluoroquinolone', '1', '1');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('cetirizine', '21000', 'antihistamine', '0', '0');
insert into public.drug_mapping (drug_name, rxcui, drug_class, mechanism_flag, risk_factor_flag) values ('metformin', '6809', 'biguanide', '0', '0');

-- grounding: interactions_seed (drug pair -> severity/mechanism/action)
insert into public.interactions_seed (drug_a, drug_b, severity, mechanism, action) values ('warfarin', 'aspirin', 'high', 'Warfarin and aspirin both impair hemostasis (coagulation + platelet inhibition), significantly increasing bleeding risk, especially GI hemorrhage.', 'Monitor INR and signs of bleeding; discuss with prescriber before combining.');
insert into public.interactions_seed (drug_a, drug_b, severity, mechanism, action) values ('warfarin', 'ibuprofen', 'high', 'NSAIDs add an antiplatelet effect and can irritate the gastric mucosa, compounding warfarin-induced bleeding risk.', 'Avoid combination where possible; monitor INR and GI bleeding signs.');
insert into public.interactions_seed (drug_a, drug_b, severity, mechanism, action) values ('warfarin', 'clarithromycin', 'high', 'Clarithromycin inhibits CYP2C9/CYP3A4 metabolism of warfarin, raising INR and bleeding risk.', 'Monitor INR closely during and after the antibiotic course; consider an alternative antibiotic.');
insert into public.interactions_seed (drug_a, drug_b, severity, mechanism, action) values ('warfarin', 'fluconazole', 'high', 'Fluconazole inhibits CYP2C9, decreasing warfarin metabolism and increasing INR.', 'Reduce warfarin dose under prescriber guidance and monitor INR frequently.');
insert into public.interactions_seed (drug_a, drug_b, severity, mechanism, action) values ('simvastatin', 'clarithromycin', 'high', 'Clarithromycin inhibits CYP3A4, blocking simvastatin clearance and raising the risk of myopathy/rhabdomyolysis.', 'Avoid coadministration; hold simvastatin for the duration of the clarithromycin course.');
insert into public.interactions_seed (drug_a, drug_b, severity, mechanism, action) values ('simvastatin', 'gemfibrozil', 'high', 'Gemfibrozil inhibits simvastatin glucuronidation, greatly increasing myopathy and rhabdomyolysis risk.', 'Avoid combination; use an alternative fibrate or statin.');
insert into public.interactions_seed (drug_a, drug_b, severity, mechanism, action) values ('digoxin', 'amiodarone', 'high', 'Amiodarone reduces digoxin clearance and displaces digoxin from tissue binding, raising serum digoxin levels and toxicity risk.', 'Reduce digoxin dose and monitor serum digoxin levels.');
insert into public.interactions_seed (drug_a, drug_b, severity, mechanism, action) values ('digoxin', 'verapamil', 'high', 'Verapamil inhibits P-glycoprotein-mediated digoxin elimination, raising digoxin levels and toxicity risk.', 'Monitor digoxin levels; reduce dose if combined.');
insert into public.interactions_seed (drug_a, drug_b, severity, mechanism, action) values ('methotrexate', 'trimethoprim', 'high', 'Both are antifolates; coadministration increases the risk of severe bone-marrow suppression and pancytopenia.', 'Avoid combination; use an alternative antibiotic.');
insert into public.interactions_seed (drug_a, drug_b, severity, mechanism, action) values ('lithium', 'ibuprofen', 'high', 'NSAIDs reduce renal lithium clearance, raising lithium levels into the toxic range.', 'Monitor lithium levels; prefer alternative analgesia.');
insert into public.interactions_seed (drug_a, drug_b, severity, mechanism, action) values ('lisinopril', 'spironolactone', 'high', 'ACE inhibitor plus potassium-sparing diuretic raises serum potassium, risking hyperkalemia and arrhythmia.', 'Monitor potassium and renal function; avoid in renal impairment.');
insert into public.interactions_seed (drug_a, drug_b, severity, mechanism, action) values ('theophylline', 'ciprofloxacin', 'high', 'Ciprofloxacin inhibits CYP1A2, slowing theophylline clearance and causing toxicity (nausea, seizures, arrhythmia).', 'Monitor theophylline levels; reduce dose.');
insert into public.interactions_seed (drug_a, drug_b, severity, mechanism, action) values ('sertraline', 'tramadol', 'high', 'Both agents raise serotonin; combined use increases serotonin syndrome risk and lowers the seizure threshold.', 'Monitor for serotonin syndrome symptoms; consider an alternative analgesic.');
insert into public.interactions_seed (drug_a, drug_b, severity, mechanism, action) values ('fluoxetine', 'phenelzine', 'critical', 'SSRI + MAOI can precipitate serotonin syndrome (hyperthermia, rigidity, agitation) — a life-threatening emergency.', 'Never combine; allow an adequate washout period between agents.');
insert into public.interactions_seed (drug_a, drug_b, severity, mechanism, action) values ('sildenafil', 'nitroglycerin', 'critical', 'PDE5 inhibitors potentiate nitrate vasodilation, causing severe, potentially fatal hypotension.', 'Contraindicated together; do not administer within 24-48 hours of nitrate use.');
insert into public.interactions_seed (drug_a, drug_b, severity, mechanism, action) values ('clopidogrel', 'omeprazole', 'moderate', 'Omeprazole inhibits CYP2C19, reducing clopidogrel activation and antiplatelet efficacy.', 'Prefer pantoprazole/rabeprazole or consider an alternative.');
insert into public.interactions_seed (drug_a, drug_b, severity, mechanism, action) values ('valproic acid', 'carbamazepine', 'moderate', 'Carbamazepine induces valproate metabolism and both compete for protein binding, altering levels and increasing toxicity.', 'Monitor drug levels and clinical response.');
insert into public.interactions_seed (drug_a, drug_b, severity, mechanism, action) values ('levothyroxine', 'calcium carbonate', 'moderate', 'Calcium binds levothyroxine in the gut, reducing absorption and impairing thyroid control.', 'Separate doses by at least 4 hours.');
insert into public.interactions_seed (drug_a, drug_b, severity, mechanism, action) values ('fluconazole', 'sertraline', 'moderate', 'Both agents prolong the QT interval; coadministration increases the risk of QT prolongation and torsades de pointes.', 'Monitor ECG; avoid if other QT-prolonging drugs are present.');
insert into public.interactions_seed (drug_a, drug_b, severity, mechanism, action) values ('acetaminophen', 'ibuprofen', 'low', 'Mild additive effect when used together; generally well tolerated at recommended doses.', 'Use the lowest effective dose; avoid exceeding daily acetaminophen limits.');
insert into public.interactions_seed (drug_a, drug_b, severity, mechanism, action) values ('amoxicillin', 'acetaminophen', 'safe', 'No clinically significant interaction reported.', 'No action required.');
insert into public.interactions_seed (drug_a, drug_b, severity, mechanism, action) values ('amoxicillin', 'ibuprofen', 'safe', 'No clinically significant interaction reported.', 'No action required.');
insert into public.interactions_seed (drug_a, drug_b, severity, mechanism, action) values ('cetirizine', 'acetaminophen', 'safe', 'No clinically significant interaction reported.', 'No action required.');
insert into public.interactions_seed (drug_a, drug_b, severity, mechanism, action) values ('metformin', 'lisinopril', 'safe', 'No clinically significant interaction; the combination is generally considered beneficial where appropriate.', 'No action required.');

-- grounding: drug_patient_risk_rules (drug + patient factor -> verdict)
insert into public.drug_patient_risk_rules (drug_name, trigger_type, trigger_condition, risk_level, effect, recommended_action) values ('Metformin', 'lab', 'eGFR<30', 'avoid', 'Risk of lactic acidosis in significant renal impairment', 'Avoid; consider an alternative antidiabetic agent');
insert into public.drug_patient_risk_rules (drug_name, trigger_type, trigger_condition, risk_level, effect, recommended_action) values ('Metformin', 'lab', 'eGFR30-45', 'caution', 'Renally cleared; accumulation risk with declining function', 'Use with caution; reduce dose and monitor renal function');
insert into public.drug_patient_risk_rules (drug_name, trigger_type, trigger_condition, risk_level, effect, recommended_action) values ('Ibuprofen', 'lab', 'eGFR<60', 'caution', 'Further renal function decline and fluid retention', 'Use lowest effective dose short-term; monitor renal function');
insert into public.drug_patient_risk_rules (drug_name, trigger_type, trigger_condition, risk_level, effect, recommended_action) values ('Warfarin', 'lab', 'INR>3', 'caution', 'Supratherapeutic INR raises bleeding risk', 'Review dose; monitor INR closely');
insert into public.drug_patient_risk_rules (drug_name, trigger_type, trigger_condition, risk_level, effect, recommended_action) values ('Lisinopril', 'lab', 'potassium>5.0', 'caution', 'Higher hyperkalemia risk', 'Monitor potassium; consider dose adjustment');
insert into public.drug_patient_risk_rules (drug_name, trigger_type, trigger_condition, risk_level, effect, recommended_action) values ('Spironolactone', 'lab', 'potassium>5.0', 'avoid', 'Risk of severe hyperkalemia', 'Avoid; reassess potassium before starting');
insert into public.drug_patient_risk_rules (drug_name, trigger_type, trigger_condition, risk_level, effect, recommended_action) values ('Ibuprofen', 'condition', 'peptic_ulcer_disease', 'caution', 'Increased GI bleeding/ulceration risk', 'Use gastroprotection or avoid; consider acetaminophen');
insert into public.drug_patient_risk_rules (drug_name, trigger_type, trigger_condition, risk_level, effect, recommended_action) values ('Aspirin', 'condition', 'peptic_ulcer_disease', 'caution', 'Increased GI bleeding risk', 'Add gastroprotection or avoid; weigh cardiovascular benefit');
insert into public.drug_patient_risk_rules (drug_name, trigger_type, trigger_condition, risk_level, effect, recommended_action) values ('Propranolol', 'condition', 'asthma', 'avoid', 'Non-selective beta-blockade can precipitate bronchospasm', 'Avoid; use a cardioselective agent if beta-blockade is essential');
insert into public.drug_patient_risk_rules (drug_name, trigger_type, trigger_condition, risk_level, effect, recommended_action) values ('Metformin', 'condition', 'chronic_kidney_disease', 'caution', 'Accumulation risk in renal impairment', 'Check eGFR and adjust accordingly');
insert into public.drug_patient_risk_rules (drug_name, trigger_type, trigger_condition, risk_level, effect, recommended_action) values ('Lisinopril', 'condition', 'hyperkalemia_history', 'avoid', 'ACE inhibitors worsen hyperkalemia', 'Avoid; consider an alternative antihypertensive');
insert into public.drug_patient_risk_rules (drug_name, trigger_type, trigger_condition, risk_level, effect, recommended_action) values ('Spironolactone', 'condition', 'hyperkalemia_history', 'avoid', 'Risk of severe hyperkalemia', 'Avoid; consider an alternative');
insert into public.drug_patient_risk_rules (drug_name, trigger_type, trigger_condition, risk_level, effect, recommended_action) values ('Amoxicillin', 'allergy', 'penicillin_allergy', 'avoid', 'Cross-reactivity with penicillin allergy', 'Avoid; consider a non-beta-lactam alternative');
insert into public.drug_patient_risk_rules (drug_name, trigger_type, trigger_condition, risk_level, effect, recommended_action) values ('Ciprofloxacin', 'allergy', 'fluoroquinolone_allergy', 'avoid', 'Documented allergy to fluoroquinolones', 'Avoid; select an alternative antibiotic');
insert into public.drug_patient_risk_rules (drug_name, trigger_type, trigger_condition, risk_level, effect, recommended_action) values ('Warfarin', 'pregnancy', 'pregnant', 'avoid', 'Known teratogenic risk', 'Avoid in pregnancy; discuss alternative anticoagulation');
insert into public.drug_patient_risk_rules (drug_name, trigger_type, trigger_condition, risk_level, effect, recommended_action) values ('Lisinopril', 'pregnancy', 'pregnant', 'avoid', 'ACE inhibitors are contraindicated in pregnancy', 'Avoid in pregnancy; switch to a pregnancy-safe antihypertensive');
insert into public.drug_patient_risk_rules (drug_name, trigger_type, trigger_condition, risk_level, effect, recommended_action) values ('Ibuprofen', 'pregnancy', 'breastfeeding', 'caution', 'Use near term is associated with fetal risks', 'Use only if clearly needed; avoid near term');
insert into public.drug_patient_risk_rules (drug_name, trigger_type, trigger_condition, risk_level, effect, recommended_action) values ('Diazepam', 'age', 'age_gt_65', 'caution', 'Higher fall/confusion risk in older adults', 'Use lowest dose; monitor for sedation and falls');
insert into public.drug_patient_risk_rules (drug_name, trigger_type, trigger_condition, risk_level, effect, recommended_action) values ('Diphenhydramine', 'age', 'age_gt_65', 'caution', 'Anticholinergic burden; higher confusion/fall risk in older adults', 'Prefer non-anticholinergic alternatives');


